Feature: Tests from MyFirstEditor.rt
  This file was autogenerated.
  It aims to avoid collisions, not remove redundancy.
  You can probably consolidate a lot of the elements.




  Scenario: MyFirstEditor is added to your project by AddMyFirstEditor
    Given the archive root
    When MyFirstEditor inputParameteristhe inputParameter value for MyFirstEditor is added to your project by AddMyFirstEditor
    Then parameters were valid
    Then changes were made
    Then fileContains hello txt Hello Worldnot for MyFirstEditor is added to your project by AddMyFirstEditor
